name: CI

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  test:
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     surrealdb-version:
    #       - ""
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: go mod download

      - run: go test -v ./...
